Repository mojohaus/sql-maven-plugin, pull requests merged in 2024-02, with the labels that each got.

#56 Update maven-script-interpreter to 1.4
  pom.xml
  src/it/msql-76/verify.groovy
  src/main/java/org/codehaus/mojo/sql/SqlExecMojo.java
Labels: dependencies

#57 Fix build and project improvements
  pom.xml
  src/it/msql-51/test.properties
  src/it/settings-security.xml
  src/it/settings.xml
  src/main/resources/META-INF/plexus/components.xml
Labels: maintenance

#60 Added connection retry functionaliy
  src/it/connection-retry/invoker.properties
  src/it/connection-retry/pom.xml
  src/main/java/org/codehaus/mojo/sql/SqlExecMojo.java
  src/test/java/org/codehaus/mojo/sql/SqlExecMojoTest.java
Labels: enhancement
